### ISSUE TITLE
删除写成了添加

### ISSUE THREAD

**Issue by xiaoahuaya** [apache/doris-website#1002]
https://doris.apache.org/zh-CN/docs/sql-manual/sql-statements/Cluster-Management-Statements/ALTER-SYSTEM-DROP-FOLLOWER/

添加一个 FOLLOWER节点

ALTER SYSTEM DROP FOLLOWER "host_ip:9010"

![image](https://github.com/user-attachments/assets/63934df5-28b7-41e9-8ad9-631dde7473da)
中英文都有问题

**Comment by KassieZ** [comment]
Thanks for the feedback, we have fix the typo.

You could follow the progress of PR through the link: https://github.com/apache/doris-website/pull/1013
