### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by LittleTemple** [apache/doris-website#1025]
Path:/zh-CN/docs/table-design/data-model/aggregate
![image](https://github.com/user-attachments/assets/3cc3b505-52c6-4aad-b353-e4c68d270d8b)
use this example but give me a error like this:
![image](https://github.com/user-attachments/assets/b6267302-7105-4d99-acf1-80de028a97b5)

**Comment by BiteTheDDDDt** [comment]
2.0和2.1语法不一样
