### ISSUE TITLE
名为‘hudi’的catalog，但是代码中catalog为hive

### ISSUE THREAD

**Issue by suxiaogang223** [apache/doris-website#1034]
位置：https://doris.apache.org/zh-CN/docs/gettingStarted/tutorials/building-lakehouse/doris-hudi
<img width="824" alt="image" src="https://github.com/user-attachments/assets/d5aafea1-6bda-4402-b1ad-5206ee73baea">

**Comment by KassieZ** [comment]
Thank you for the feedback, will fix it ASAP
