### ISSUE TITLE
Meta Service API 参考-计算集群添加节点-请求参数

### ISSUE THREAD

**Issue by chenyz1984** [apache/doris-website#1068]
[计算集群添加节点](https://doris.apache.org/zh-CN/docs/compute-storage-decoupled/meta-service-api/#%E8%AE%A1%E7%AE%97%E9%9B%86%E7%BE%A4%E6%B7%BB%E5%8A%A0%E8%8A%82%E7%82%B9)
![image](https://github.com/user-attachments/assets/6d421c37-c563-4163-9320-f39ddc0a0d35)

**Comment by KassieZ** [comment]
Hi, thank you for the feedback, could you elaborate more details about your question ?

**Comment by chenyz1984** [comment]
Should it be the IP or domain name of the host？

**Comment by gavinchou** [comment]
@chenyz1984 
We cannot leave the field `ip` empty for now.
It should be domain name of the host if you run Doris in FQDN mode.
