### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by 13057537919** [apache/doris-website#1069]
Path:/zh-CN/docs/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-TABLE-LIKE
前置：doris已构建超管权限的mysql外部表
目的：复制外部表到doris
语句：CREATE EXTERNAL TABLE IF NOT EXISTS dexpdb.trade_record LIKE titandb_32.titandb.trade_record
问题：SQL 错误 [1105] [HY000]: errCode = 2, detailMessage = External catalog 'titandb_32' is not allowed in 'CreateTableLikeStmt'

疑问：怎么解决？

**Comment by morningman** [comment]
Try
1. `switch internal`
2. `CREATE EXTERNAL TABLE IF NOT EXISTS dexpdb.trade_record LIKE titandb_32.titandb.trade_record`
