### ISSUE TITLE
采用with 写法，不能用insert，只能将源表select语句拼接在insert后面才能执行。脚本写的非常不优雅

### ISSUE THREAD

**Issue by 13057537919** [apache/doris-website#1071]
Path:/zh-CN/docs/data-operate/import/insert-into-manual
![49b2d0087b857341acf067295d9b7b8](https://github.com/user-attachments/assets/655e3228-b28d-46b0-867d-0769aadf7251)
![336a1b8ab006509d19b37f841c3bf30](https://github.com/user-attachments/assets/0bc3957a-37f2-4645-88a0-660e182d33f2)

**Comment by 13057537919** [comment]
这么写才能成功，测试出with写法不支持与insert联用 
INSERT into dexpdb.ods_asystem_mysql_goods_baseinfo   select * from titandb_32.titandb.goods_baseinfo where id BETWEEN (select breakpoint from  dexpdb.dexp_access_breakpoint where source_table_name = 'titandb_32.titandb.goods_baseinfo' and sink_table_name ='dexpdb.ods_asystem_mysql_goods_baseinfo' order by ts desc limit 1) and (select max(id) as currentpoint from titandb_32.titandb.goods_baseinfo );

**Comment by KassieZ** [comment]
Hi, thank you for the feedback, will report this issue to engineer ASAP
