### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by daydayupon** [apache/doris-website#1096]
Path:/zh-CN/docs/1.2/sql-manual/sql-reference/Data-Manipulation-Statements/Load/CREATE-ROUTINE-LOAD
为什么文档中说明可以使用自定义函数做列转换，但是我在routine load里面列转换使用自己的udf就是显示不生效呢，一直报ErrorReason{code=errCode = 2, msg='failed to create task: errCode = 2, detailMessage = Does not support non-builtin functions, or function does not exist: get_region('aa')'}的异常，但是我直接select get_region('aa')又是可以正常调用的，请问是什么问题?

**Comment by KassieZ** [comment]
Hi, thank you for the feedback, will update the issue to engineer. btw, you can also go to [doris forum ](https://ask.selectdb.com) for asking question and troubleshooting

**Comment by KassieZ** [comment]
Hi, version 1.2 not supports loading data with udf function, the pr here will show you how to use a global configuration to support. https://github.com/apache/doris/pull/43029
