### ISSUE TITLE
1.2版本中提到的delete from t using 语法在1.2.8版本中执行报错

### ISSUE THREAD

**Issue by chengwei977** [apache/doris-website#1120]
[Path:false]链接：(https://doris.apache.org/zh-CN/docs/1.2/sql-manual/sql-reference/Data-Manipulation-Statements/Manipulation/DELETE/?_highlight=delete)

使用以上官方链接在1.2.8版本中执行失败。报错图下：
![微信图片_20240918145642](https://github.com/user-attachments/assets/bdd47393-bee2-4a4f-ae58-fa029bdcc770)

**Comment by chengwei977** [comment]
测试了下，2.0.14版本没这个问题。是否1.2还未提供该功能

**Comment by KassieZ** [comment]
报错问题可以前往 [Doris中文论坛](https://ask.selectdb.com)反馈，有技术人员支持
