### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by lzzcj** [apache/doris-website#1158]
Path:/zh-CN/docs/2.0/sql-manual/sql-reference/Data-Definition-Statements/Backup-and-Restore/CREATE-REPOSITORY

在线文档中
CREATE REPOSITORY `minio_repo`
WITH S3
ON LOCATION "s3://minio_repo"
PROPERTIES
(
    "s3.endpoint" = "http://minio.com",
    "s3.access_key" = "MINIO_USER",
    "s3.secret_key"="MINIO_PASSWORD",
    "s3.region" = "REGION"
    "use_path_style" = "true"
);

"s3.region" = "REGION"后面少了个逗号

**Comment by KassieZ** [comment]
Thank you for the feedback, will fix it ASAP
