### ISSUE TITLE
公用表表达式（CTE）不支持 INSERT INTO TBL_NAME 

### ISSUE THREAD

**Issue by xqg1316** [apache/doris-website#1171]
Path:/zh-CN/docs/query/query-data/cte

不支持 
INSERT INTO tbl_name
WITH
  cte1 AS (SELECT a，b FROM table1)，
  cte2 AS (SELECT c，d FROM table2)
SELECT b，d 
FROM cte1 
JOIN cte2
WHERE cte1.a = cte2.c;

**Comment by morrySnow** [comment]
什么版本？报什么错？

**Comment by morrySnow** [comment]
<img width="1360" alt="image" src="https://github.com/user-attachments/assets/53b6cc7c-83db-4aaf-aa98-cf14813fdca0">

**Comment by xqg1316** [comment]
版本 2.1.3

这个链接中有具体的提问：https://github.com/apache/doris/issues/41491

**Comment by morrySnow** [comment]
@xqg1316 #41491 中没有完整复现方式。构造简单case并不能复现所述问题
