### ISSUE TITLE
markdown 引用有问题？

### ISSUE THREAD

**Issue by creazyboyone** [apache/doris-website#1206]
备份操作会备份指定表或分区的基础表及同步物化视图[物化视图](https://doris.apache.org/zh-CN/docs/query/view-materialized-view/materialized-view.md)，并且仅备份一副本，异步物化视图(../../../../query/view-materialized-view/async-materialized-view.md)当前未支持。

**Comment by KassieZ** [comment]
Hi, thank you for the feedback, will fix the link ASAP

**Comment by creazyboyone** [comment]
陌生人发邮件来了

**Comment by KassieZ** [comment]
Hi, the link was invalid and markdown format was wrong. Fixed it already, please check later: https://github.com/apache/doris-website/pull/1271
