### ISSUE TITLE
load data，csv的数据中包含分隔符，enclose指定了也没用

### ISSUE THREAD

**Issue by physym** [apache/doris-website#1228]
csv文件其中一行数据：
...
a|b|c|"d|e"|f
...
使用以下命令导入
load data local infile 'test.csv'
into table test
columns terminated by '|'
lines terminated by '\n'
ignore 1 rows
properties ("enclose"="\\"","trim_double_quotes"="true")
执行后报错，提示数据被分成了6列，应该是5列，也就是enclose没有起作用

**Comment by physym** [comment]
是哪边写错了吗？

**Comment by KassieZ** [comment]
感谢反馈，有关问题报错，可前往[中文技术论坛](ask.selectdb.com)，会有专人支持解答。关于文档问题，可附上文档链接，我们将记录并及时修改

**Comment by freemandealer** [comment]
@TangSiyang2001  Call of duty

**Comment by TangSiyang2001** [comment]
@physym 这种情况下似乎不需要指定enclose，不过"d里的`"`应该是去不掉的

**Comment by physym** [comment]
> @physym 这种情况下似乎不需要指定enclose，不过"d和e"里的`"`应该是去不掉的

我重点不是要去掉双引号，而是导入失败，解析字段列数会多一个，不指定enclose，就报错了

**Comment by physym** [comment]
误操作，重开
