### ISSUE TITLE
[Doc] Markdown typo at transaction blog

### ISSUE THREAD

**Issue by Jake-00** [apache/doris-website#1257]
## Description
There are redundant indentations in code block, which cause confused existence of markdwon syntax.
<img width="822" alt="image" src="https://github.com/user-attachments/assets/d39e5dbb-3158-4b8e-92fb-e443971f544d">

## Influence Scope 
Four md files have same indentation issue.
<img width="447" alt="image" src="https://github.com/user-attachments/assets/0fe98fe6-9958-41b4-bdfa-192f0d86bce6">

**Comment by Jake-00** [comment]
Moreover, two transaction blogs under version-2.1 also meet the same problem. Files' path shown below.
1. i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/data-operate/transaction.md
2. versioned_docs/version-2.1/data-operate/transaction.md

**Comment by Jake-00** [comment]
# 1258

**Comment by KassieZ** [comment]
Thank you for the feedback and contribution. The change will merge today.
