### ISSUE TITLE
Issue on docs：url 404 error

### ISSUE THREAD

**Issue by chenyz1984** [apache/doris-website#1275]
Path:/zh-CN/docs/sql-manual/sql-statements/Data-Definition-Statements/Create/CREATE-RESOURCE

The url：https://doris.apache.org/zh-CN/docs/lakehouse/multi-catalog/multi-catalog.md 404 error, see as below:

![image](https://github.com/user-attachments/assets/c1d39ec1-a2cd-449d-9c6b-08ad2a4415f9)

**Comment by KassieZ** [comment]
Hi，thank you for the feedback, fixed it already and will merge ASAP: https://github.com/apache/doris-website/pull/1271
