### ISSUE TITLE
load Execute timeout ，内存未释放

### ISSUE THREAD

**Issue by daxiong123a** [apache/doris-website#1305]
Path:/zh-CN/docs/2.0/releasenotes/v2.1/release-2.1.5

load Execute timeout ，内存未释放
![load-error](https://github.com/user-attachments/assets/5ff92dc7-b9b3-4fd3-97e2-0f6e7cca2569)

**Comment by KassieZ** [comment]
感谢反馈，可前往[中文技术论坛](ask.selectdb.com)有专人支持问题解答。
