### ISSUE TITLE
[404] This page is not found 

### ISSUE THREAD

**Issue by laglangyue** [apache/doris-website#372]
https://doris.apache.org/zh-CN/docs/sql-manual/sql-reference/Show-Statements/SHOW-LOAD.md

go to
https://doris.apache.org/zh-CN/docs/sql-manual/sql-reference/Data-Manipulation-Statements/Load/BROKER-LOAD#keywords
and this link will get 404
![image](https://github.com/apache/doris-website/assets/35491928/b05e3868-d82f-469c-a64a-d63e300d40a6)

**Comment by laglangyue** [comment]
besides, more link of this Page will get 404
in 2.0

**Comment by KassieZ** [comment]
> besides, more link of this Page will get 404 in 2.0

Hihi, thanks for the feedback, link will be revise ASAP.
