### ISSUE TITLE
“通过外部表同步数据"的CREATE EXTERNAL TABLE 链接为空

### ISSUE THREAD

**Issue by anthony-yau** [apache/doris-website#420]
该文档：https://doris.apache.org/zh-CN/docs/data-operate/import/import-scenes/external-table-load，的请参阅 [CREATE EXTERNAL TABLE](https://doris.apache.org/zh-CN/docs/sql-manual/sql-reference/Data-Definition-Statements/Create/CREATE-EXTERNAL-TABLE.md) 命令手册，这个文档超链接打开404。

![image](https://github.com/apache/doris-website/assets/3424576/0b0032cf-99c4-4541-9535-2face956bab4)

**Comment by morningman** [comment]
external table is deprecated, try this:
https://doris.apache.org/docs/dev/lakehouse/multi-catalog

**Comment by anthony-yau** [comment]
> external table is deprecated, try this: https://doris.apache.org/docs/dev/lakehouse/multi-catalog

好的
