### ISSUE TITLE
doris-1.2 CREATE-EXTERNAL-TABLE page could not be found

### ISSUE THREAD

**Issue by comuser123** [apache/doris-website#557]
Your question: This page could not be found
Link address: https://doris.apache.org/zh-CN/docs/1.2/sql-manual/sql-reference/Data-Definition-Statements/Create/CREATE-EXTERNAL-TABLE.md

**Comment by luzhijing** [comment]
Thanks for your issue. The external table no longer maintained, and it is recommended to use Multi-Catalog as a replacement from version 1.2 onwards.

https://doris.apache.org/zh-CN/docs/1.2/sql-manual/sql-reference/Data-Definition-Statements/Create/CREATE-CATALOG
