### ISSUE TITLE
 Sequence Column page could not be found

### ISSUE THREAD

**Issue by iszhangsc** [apache/doris-website#621]
doris 2.1
 Sequence Column page could not be found

**Comment by luzhijing** [comment]
https://doris.apache.org/docs/data-operate/update/unique-update-transaction#sequence-column

**Comment by luzhijing** [comment]
Thank you for your issue. The document refactoring work is currently underway. If any internal links in the document are found to be invalid, please provide the URL of the document page. Thank you.
