### ISSUE TITLE
logstash导入数据到doris中，format不支持

### ISSUE THREAD

**Issue by Volcano139** [apache/doris-website#638]
我在使用logstash导入kafka中的数据到doris中，数据格式为json，但是配置无法识别
output {
    doris {
        http_hosts => [ "xxx" ]
        user => root
        password => ""
        db => "log"
        table => "k8s_log"
        format => "json"
   }
}
报错
[2024-05-12T00:37:09,755][ERROR][logstash.outputs.doris   ] Unknown setting 'format' for doris

logstash版本为8.13.4
配置了./bin/logstash-plugin install logstash-output-doris-1.0.0.gem

**Comment by luzhijing** [comment]
https://doris.apache.org/zh-CN/docs/data-operate/import/load-json-format

Currently, only the following import methods support data import in JSON format:

Through [S3 table function](https://doris.apache.org/sql-manual/sql-functions/table-functions/s3.md) import statement: insert into table select * from S3();
Import the local JSON format file through [STREAM LOAD](https://doris.apache.org/sql-manual/sql-reference/Data-Manipulation-Statements/Load/STREAM-LOAD.md).
Subscribe and consume JSON format in Kafka via [ROUTINE LOAD](https://doris.apache.org/sql-manual/sql-reference/Data-Manipulation-Statements/Load/CREATE-ROUTINE-LOAD.md) information.
Other ways of importing data in JSON format are not currently supported.
