### ISSUE TITLE
DROP-TABLE 介绍里面：详见 RECOVER 语句跳转链接不对

### ISSUE THREAD

**Issue by a110q** [apache/doris-website#719]
![image](https://github.com/apache/doris-website/assets/93298332/12030689-2f01-4991-9dfc-6d9ae568fd7c)

跳转地址为：
https://doris.apache.org/zh-CN/docs/sql-manual/sql-reference/Database-Administration-Statements/RECOVER.md

正确地址应为：
https://doris.apache.org/zh-CN/docs/sql-manual/sql-statements/Database-Administration-Statements/RECOVER

**Comment by KassieZ** [comment]
Hi， thank you for you feedback, the typo has been fixed. Please refer to : https://github.com/apache/doris-website/pull/1091
