### ISSUE TITLE
Incomplete Documentation in Hive Section of Doris Lakehouse

### ISSUE THREAD

**Issue by LiranEliyahu** [apache/doris-website#722]
Under "Lakehouse > Building Data Lake > Hive" there are two segments that include a "TODO" placeholder, which means an incomplete documentation.
See following link: https://doris.apache.org/docs/lakehouse/datalake-building/hive-build/
( ctrl + f  TODO)

![image](https://github.com/apache/doris-website/assets/69078650/03b54160-7650-4b82-9f66-fbc44835734a)
![image](https://github.com/apache/doris-website/assets/69078650/7160b265-75ee-4d6d-9193-fd76bffbf5d8)

DoD - The “TODO” statements have been successfully replaced with the missing documentation

**Comment by KassieZ** [comment]
Hi, thank you for your feedback, we will complete the docs ASAP

**Comment by morningman** [comment]
This content are currently empty, I remove them temporary, will be added once needed
