### ISSUE TITLE
外表导入链接为空

### ISSUE THREAD

**Issue by taofenghao** [apache/doris-website#734]
中文版文档链接为空
![image](https://github.com/apache/doris-website/assets/3676538/9905dd97-4d09-4929-8758-1ac861303a54)

https://doris.apache.org/zh-CN/docs/dev/data-operate/import/load-manual/insert-into-manual

**Comment by shasevendow** [comment]
已修复为：https://doris.apache.org/zh-CN/docs/dev/data-operate/import/insert-into-manual
