### ISSUE TITLE
Compilation Guide Not Found

### ISSUE THREAD

**Issue by tiany7** [apache/doris-website#752]
# Issue
The resource associated with this link could no longer be found.

<img width="641" alt="image" src="https://github.com/apache/doris-website/assets/46698520/09557e9f-e771-42ed-9af6-cc0d3f446db0">
# Link
https://doris.apache.org/zh-CN/docs/dev/install/source-install/compilation-general

**Comment by shasevendow** [comment]
Hi tiany7, thanks for your reporting. Can you please provide the document where this invalid link is attached?
