### ISSUE TITLE
the demo of   dynamic_partition.start  description error

### ISSUE THREAD

**Issue by renpeipei** [apache/doris-website#852]
in this dynamic partition table demo, dynamic_partition.start should be -7,not 7。
![20240711105353501](https://github.com/apache/doris-website/assets/32954717/dacedb03-028d-4d3f-a9b1-fce7d83c1e8f)

**Comment by KassieZ** [comment]
Hi, thank you for feedback, we will double check whether is 7 or -7 then fix the description

**Comment by KassieZ** [comment]
Hi, thank you for waiting, fixed it already : https://github.com/apache/doris-website/pull/1271
