### ISSUE TITLE
[Bug] Releases pages 404ing e.g https://doris.apache.org/docs/releasenotes/release-3.0.0

### ISSUE THREAD

**Issue by johnpyp** [apache/doris-website#965]
I think something must've changed with the releases schema, but urls in search engines like Google seem to be broken for releases. For example, searching "Doris 3.0" and clicking the releases link gives me this 404 page - https://doris.apache.org/docs/releasenotes/release-3.0.0

Not sure if this is a problem with Google outdated links or Doris website surfacing the wrong links / bad sitemap. Could be both.

**Comment by KassieZ** [comment]
Great feedback and thank you !
Yes, there are some changes of docs schema. We will update the sitemap and also submit the oudated links to google search console ASAP
