### ISSUE TITLE
build_help_zip.sh is invalid

### ISSUE THREAD

**Issue by binarytom** [apache/doris-website#991]
I found here is a script [build_help_zip](https://github.com/apache/doris/blob/master/docs/build_help_zip.sh) in doris repository.

But I found the sql-manual files has been move here. 
So the script is invalid. 
And I wanna ask whether we need to provide the script here?

**Comment by KassieZ** [comment]
Hi, thanks for reaching out to us. 
The HELP script has been deprecated, and the follow-up is currently being refactored.
